version: '3.1'
services:
  # Service database
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - .docker/dbdata:/data/db
  # Client mongo express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
